CREATE TABLE answer (
id VARCHAR(43) CONSTRAINT PK_ANSWER PRIMARY KEY NOT NULL,
question_id VARCHAR(43) NOT NULL,
correct BOOLEAN NOT NULL,
answer TEXT NOT NULL,
--answer_uuid VARCHAR(43) NOT NULL,
FOREIGN KEY (question_id) REFERENCES question(id));