CREATE TABLE question (
a_id INTEGER CONSTRAINT PK_QA PRIMARY KEY AUTOINCREMENT NOT NULL,
id VARCHAR(43) NOT NULL,
user_email VARCHAR(43) NOT NULL,
topic_id VARCHAR(43) NOT NULL,
question TEXT,
rating INTEGER DEFAULT 0 NOT NULL,
rate_count INTEGER DEFAULT 0 NOT NULL,
difficulty INTEGER DEFAULT 1 NOT NULL,
FOREIGN KEY (user_email) REFERENCES user(email),
FOREIGN KEY (topic_id) REFERENCES topic(id));